Feature: HU39455 Crear los diferentes escenarios para automatizar las pruebas

  @AgregarConReferencia
  Scenario Outline: Casos de prueba Agregar RCE Guias recogidas por Coordinadora
    Given Agregar con referencia que soy un usuario de GDE tipificado con referencia <cp> <usuario> <contrasena>
    When Agregar con referencia en la api cambio de valor de GDE, envio una referencia perteneciente a una guia con nivel de servicio uno estado diferente a recibir por coordinadora, antes de autorizar a carga de trabajo, con el campo valor mayor que cero <referencia> <valar> <autorizada>
    Then Agregar con referencia se realiza el respectivo proceso de agregar el registro del recaudo en la tabla recaudos registro de la guia en dicha tabla dejando el campo valor_total con el calor enviado en el campo valor del body de la Api, se cambia el nivel de servicio uno a veintidos en la tabla remesas_niveles_servicio campo nivel_servicio y se modifica la guia en la tabla generacion_rotulos cambiando el campo codigo_nivel_servicio por veintidos, el campo nivel_servicio por Recaudos Contra Entrega y el campo recaudo por el valor a recaudar enviado en el campo valor del body de la Api, estas tres tablas pertenecientes a la base de datos CM Testing ciento veinte a su vez se inserta la guia en la coleccion llamada cambios_valor_agw del proyecto cm_guias_test de firestore, con el campo llamado estado igual a pendiente y cuando el reloj marque un minuto terminado en cero o en cinco, se correra una tarea que realizara la insercion del registro de la guia en la tabla agw_recaudos con el campo campo valor de esa tabla igual al valor enviando en el campo valor del body de la Api, se modifica el nivel de servicio en la tabla agw_remisiones_niveles_servicio dejando el nivel de servicio veintidos en el campo nivel_servicio, estas dos tablas pertenecientes a la base de datos de sandbox_agw reflejando por ultimo una respuesta de con el estado Recaudo insertado, el valorAnterior del RCE y el Valor Nuevo Si el cliente esta tipificado codigo_remision devuelve el campo codigoRemision con el numero de guia y los campos referencia y referenciaDetalle vacios, si el cliente es tipificado referencia devuelve el campo codigoRemision con el numero de guia, el campo referencia con la referencia de la guia la cual se envia en el body de la api, y el campo referenciaDetalle vacio, si el cliente es tipificado referencia y referenciaDetalle devuelve el campo codigoRemision con el numero de guia, el campo referencia con la referencia que se envia en el body de la api, y el campo referenciaDetalle con la referenciaDetalle que se envia en el body de la api <mensaje> <status>

    Examples:
      | cp                                                                                                         | usuario          | contrasena | referencia | valar  | mensaje             | status | autorizada |
      | "TC13. Verificar que se agregue el RCE a una guia con nivel de servicio 1 - Antes de autorizar"            | "cvecommerce.ws" | "Kli3$89h" | "mateo8"   | 900000 | "Recaudo insertado" |    200 |          0 |
      | "TC16. Verificar que se agregue el RCE a una guia con nivel de servicio 1 - autorizada a carga de trabajo" | "cvecommerce.ws" | "Kli3$89h" | "mateo10"  | 900000 | "Recaudo insertado" |    200 |          1 |
      # | "TC14. Verificar que se agregue el RCE a una guia con nivel de servicio 26 - Antes de autorizar"            | "cvecommerce.ws" | "Kli3$89h"  | "6565625656" |   1000 | "Recaudo insertado" |         200 ||
      # | "TC15. Verificar que se agregue el RCE a una guia con nivel de servicio 19 - Antes de autorizar"            | "cvecommerce.ws" | "Kli3$89h"  | "6565625656" |   1000 | "Recaudo insertado" |         200 ||
      # | "TC17. Verificar que se agregue el RCE a una guia con nivel de servicio 26 - autorizada a carga de trabajo" | "cvecommerce.ws" | "Kli3$89h"  | "6565625656" |   1000 | "Recaudo insertado" |         200 ||
      # | "TC18. Verificar que se agregue el RCE a una guia con nivel de servicio 19 - autorizada a carga de trabajo" | "cvecommerce.ws" | "Kli3$89h"  | "6565625656" |   1000 | "Recaudo insertado" |         200 ||
