Feature: HU39455 Crear los diferentes escenarios para automatizar las pruebas

  @ModificacionConReferencia
  Scenario Outline: Casos de prueba Modificación RCE Guias recogidas por Coordinadora
    Given Modificar con referencia que soy un usuario de GDE tipificado con referencia <cp> <usuario> <contrasena>
    When Modificar con referencia en la api cambio de valor de GDE, envio una referencia perteneciente a una guia con nivel de servicio veintidos estado diferente a recibir por coordinadora, antes de autorizar a carga de trabajo, con el campo valor mayor que cero <referencia> <valor> <autorizada>
    Then Modificar con referencia se realiza el respectivo proceso de modificar el valor del recaudo en la tabla recaudos campo valor_total por el nuevo valor asignado y en la tabla generacion_rotulos campo recaudo por el nuevo valor asignado. Estas dos tablas pertenecientes a la base de datos CM Testing ciento veinte, a su vez se inserta la guia en la coleccion llamada cambios_valor_agw del proyecto cm_guias_test de firestore, con el campo llamado estado igual a pendiente y cuando el reloj marque un minuto terminado en cero o en cinco, se correra una tarea que realizara el cambio del valor a recaudar en la tabla agw_recaudos campo valor, esta tabla en la base de datos de sandbox_agw. reflejando por ultimo una respuesta de con el estado Recaudo actualizado, el valorAnterior del RCE y el Valor Nuevo Si el cliente esta tipificado codigo_remision devuelve el campo codigoRemision con el numero de guia y los campos referencia y referenciaDetalle vacios, si el cliente es tipificado referencia devuelve el campo codigoRemision con el numero de guia, el campo referencia con la referencia de la guia la cual se envia en el body de la api, y el campo referenciaDetalle vacio, si el cliente es tipificado referencia y referenciaDetalle devuelve el campo codigoRemision con el numero de guia, el campo referencia con la referencia que se envia en el body de la api, y el campo referenciaDetalle con la referenciaDetalle que se envia en el body de la api <mensaje> <status>

    Examples:
      | cp                                                                                                | usuario          | contrasena | referencia | valor  | mensaje               | status | autorizada |
      | "TC10 Verificar que se modifique el RCE a una guia con nivel de servicio 22 - antes de autorizar" | "cvecommerce.ws" | "Kli3$89h" | "Mateo1"   | 125000 | "Recaudo Actualizado" |    200 |          0 |
    #   | "TC13 Verificar que se modifique el RCE a una guia con nivel de servicio 22 - autorizada"         | "cvecommerce.ws" | "Kli3$89h" | "Mateo_2"  | 125000 | "Recaudo Actualizado" |    200 |          1 |
    #   | "TC16 Verificar que se modifique el RCE a una guia de dos unidades con nivel de servicio 22"      | "cvecommerce.ws" | "Kli3$89h" | "Mateo_3"  | 125000 | "Recaudo Actualizado" |    200 |          1 |
